### PR TITLE
Add title/job toggle

### LINKED ISSUE #13: Empty 'Title' not possible
I don't like a job title in the about me page of my personal website. So I'd like to leave it empty. However, saving an empty value in the admin panel will show the plugin default for Santa. 

A workaround is to save a space character which shows up empty. But this renders a `<h3>` section with the space.

Since reverting to the plugin default is standard Grav behaviour, I think the only option to really suppress the job title would be to create a toggle for this. If you allow a PR for this, I will submit one.

### PR DESCRIPTION
**Pull request by metbril**
Fixes #13 
Additional changes:

- fix some markdown in README
- introduced language support :-)

### CODE REVIEW

**Review by seb-vial — COMMENTED** [review]
Thank you for your PR. I do have some remarks:
- I think it would be better not to mix README changes with a PR for a feature that doesn't have anything to do with theses changes.
- Regarding README changes (which should probably be in a different PR as mentioned), except for the `Feature` title where there is a missing space between the title and the #, is it really necessary to change every title' size ?
- That's a good idea to introduce multi languages, but as the README changes, I would do it in a different PR/Commit. It might be a good idea to start with English strings for now in the `blueprints.yaml` (for this PR), and introduce the languages file with all the changes induced in an other PR

**Comment by metbril** [comment]
According to the Markdown spec, you should only have one level 1 heading in a document. So I changed/corrected/fixed that. My Markdown linter in VS Code kept complaining. ;-)

I will revert the README changes for this PR. I'll leave it up to you to fix this, since I don't like to do the work twice.

I (sort of) agree on the languages. I'll hard code the english string for now and submit another PR for the translations. That one will include all blueprint fields.

**Comment by metbril** [comment]
Done and ready for merging, I think.

**Comment by seb-vial** [comment]
Sorry I had no idea for the markdown specification, I'll fix this afterwords ;)
Thank you for the time and effort you put into this.

**Pull request merged**
